### ISSUE TITLE
Problem with time zone setting?

### ISSUE THREAD

**Issue by wrmack** [glondu/belenios#10]
When running Belenios locally kept getting error:
 ocsigenserver.opt: ocsigen:main: Exn during page generation (sending 500): Invalid_argument("2020-07-20 -20:-08:-25 does not match the format %Y-%m-%d %H:%M:%S")

(Date was actually 2020-07-26 and negative time was being produced).

This occurred after signing in and starting to create a new election after pressing "Proceed".

Corrected this by commenting out `let () = CalendarLib.Time_Zone.(change Local)` in web_main.ml.

I live in New Zealand.

Unless I have done something wrong, this code might need looking at.

**Comment by glondu** [comment]
Thank you for your report.

This is https://github.com/ocaml-community/calendar/issues/11 . Belenios only manipulates UTC times (so far) and CalendarLib defaults to UTC, so your fix is correct. Applied in 641b7306068702faa1c23d4eec6ca0f822d3f2c2 .
