### ISSUE TITLE
2000 voter maximum

### ISSUE THREAD

**Issue by aricooperdavis** [glondu/belenios#11]
Hi Stéphane et al.,

The belenios.loria.fr implementation has an upper limit of 2000 voters but there is no mention of this that I could find in the documentation on the website.

- What is the reason for this upper limit?
- Is it possible to overcome this limit by downloading and compiling belenios on your own server?

Many thanks for your help,
Ari

**Comment by glondu** [comment]
> What is the reason for this upper limit?

I would say testing. Our load testing says this limit could be around 5000 in our setting. We are (kind of) limited by mail sending anyway, so we did not really try to raise it.

> Is it possible to overcome this limit by downloading and compiling belenios on your own server?

Yes. It is a configuration setting. I would advise you to do your own load testing in this case.

**Comment by aricooperdavis** [comment]
Hi Stéphane,

Thank you for your reply.

When you mention load testing are you concerned that the mail server won't be able to deliver those emails simultaneously? 

Many thanks,
Ari

**Comment by glondu** [comment]
> When you mention load testing are you concerned that the mail server won't be able to deliver those emails simultaneously?

No, the load testing was done without sending mails. By "limited by mail sending", I meant that the mail server we use (which is not under our control) limits us in the amount of mails we can send. Mails do not need to be delivered simultaneously.
