### ISSUE TITLE
consider moving home from inria to framagit or codeberg

### ISSUE THREAD

**Issue by kanishka-work** [glondu/belenios#19]
I would contrib docs maybe twice a year to this project, but it's a little complicated getting a login to inria git (I doubt other people would bother) and I'd prefer deleting my github user.

**Comment by glondu** [comment]
We use CI on Inria's GitLab instance. For non-Inria contributions, there is this GitHub repo. You can also send your contributions via email (with git format-patch); this can be suitable in your case, for occasional contributions if you don't have an account on GitHub. We won't create a copy of Belenios on each existing hosting platform in the world...

**Comment by kanishka-work** [comment]
Okay, will learn the format-patch command eventually, and use GitHub for now. Closing the issue since you noted a plan of action.
