### ISSUE TITLE
esy might help with dune installation

### ISSUE THREAD

**Issue by kanishka-work** [glondu/belenios#20]
I assume you have already considered it, but in the off chance that you haven't, you can try using esy to install dune.

**Comment by glondu** [comment]
No, I haven't considered esy, and after looking it up... I still don't know why I would. However, people are free to use whatever package manager they want to install dune. IIUC, esy is a layer on top of npm and opam? Why do you think it deserves special treatment in the case of Belenios? IMHO, the main issue is installing npm/opam(/esy), not dune...

**Comment by kanishka-work** [comment]
From my limited experience and understanding, esy replaces npm/opam, but uses their repository formats and locations. Esy can install ocaml compiler and dune. Users would need to install npm initially to get esy installed. I don't know enough about opam to discuss tradeoffs. I noted this to see if it would reduce how many issues you get related to people initially building and installing locally. Feel free to close if you see opam as simpler, more direct

**Comment by glondu** [comment]
For people who are not knowledgeable in opam/ocaml, there is the opam-bootstrap.sh script that downloads and installs opam in a private directory (~/.belenios by default) then, once opam is installed, installs all other build-dependencies (including, but not limited to, dune). This script is very simple, and I expect anyone to be able to read it and adapt it if needed. In practice, it seems to suffice.
