### ISSUE TITLE
Behind a nginx reverse proxy - wrong url

### ISSUE THREAD

**Issue by rylebrun** [glondu/belenios#22]
I use Belenios behind a reverse proxy (nginx on port 80/443) with a domain name, but I have many references to **localhost:8001** instead my domaine name (in email template, on user interface for the vote link...). 

There is a place in the config file to fill the real domain name and overwrite the localhost:8001 ? 

Thanks,

**Comment by rylebrun** [comment]
This configuration seems work, in `ocsigenserve.conf.in` :

```
<ocsigen>
  <server>
    <port>127.0.0.1:8001</port>
    <usedefaulthostname/>
   [...]
   <host charset="utf-8" hostfilter="*" defaulthostname="vote.example.org" defaulthttpsport="443" defaultprotocol="https">
```
With a Nginx reverse-proxy (Let's Encrypt + force to HTTPS).

Peer review welcome.
Thanks !

**Comment by glondu** [comment]
If it works, then fine. For reverse-proxy situations, there is also the `<rewrite-proxy>` directive (see https://github.com/glondu/belenios/blob/master/doc/web.md).

**Comment by glondu** [comment]
I'm afraid that with your solution, there are still some HTTP requests going through, which are then redirected to HTTPS. Did you check that only HTTPS requests are made? If not, I suggest to use the following directive:

    <rewrite-prefix src="http:" dst="https:"/>

**Comment by rylebrun** [comment]
Thanks @glondu, I'll investigate on this, but Belenios listen only on localhost and Nginx force all HTTP requests to HTTPS.
