### ISSUE TITLE
Cannot send email

### ISSUE THREAD

**Issue by hwellmann** [glondu/belenios#29]
My local server build fails to send credentials emails.

In the web UI, I'm getting the following cryptic error message

```
Netchannels.Command_failure(WEXITED 127)
```

More helpful information is displayed on the console:

```
/bin/sh: 1: /usr/lib/sendmail: not found
```

My machine does not have sendmail or any other local mail service. Email gets sent via an external bulk email service. 

How can I configure Belenios to use an external SMTP service?

**Comment by glondu** [comment]
> How can I configure Belenios to use an external SMTP service?

Belenios doesn't speak SMTP directly at the moment. It needs a working `sendmail` command. You can use `dma` (or `ssmtp` or `nullmailer`) which you can configure to use any SMTP server you want.

**Comment by hwellmann** [comment]
Ok, would be helpful to add that to the prerequisites in `INSTALL.md`.

**Comment by glondu** [comment]
> Ok, would be helpful to add that to the prerequisites in `INSTALL.md`.

Done.
