### ISSUE TITLE
Customize email sender name

### ISSUE THREAD

**Issue by hwellmann** [glondu/belenios#30]
All emails sent by Belenios have the sender name `Belenios public server`.

I tried to customize this by setting

```
<server mail="MyOrg Voting Server <voting@my.org>"/>
```

which results in

```
ocsigenserver.opt: ocsigen:main: Fatal - Error in configuration file: Error while parsing configuration file: Eliom: while loading _run/usr/lib/belenios-server/belenios_server.cmxs: execution of module initializers in the shared library failed: Failure("MyOrg Voting Server <voting@my.org> is not a valid e-mail address")
```

**Comment by glondu** [comment]
You can now (as of 381309c) achieve this with:

    <server name="MyOrg Voting Server" mail="my.org"/>

**Comment by hwellmann** [comment]
Perfect. You might want to add the new attribute to `demo/ocsigenserver.conf.in` for reference.
