### ISSUE TITLE
credgen: Implementation does not match specification

### ISSUE THREAD

**Issue by hwellmann** [glondu/belenios#31]
According to Section 4.7 of the specification

> A secret credential _c_ is a 15-character string

This implies that the hyphens in a secret credential like `NYC-SgM-axC-fCu-pvP` are just for convenience of the human reader.

However,

```
belenios-tool credgen --derive=NYC-SgM-axC-fCu-pvP --group=files/groups/default.json --uuid=deT9e32LvYeDzg
```

does not seem to remove the hyphens or validate the credential format at all before passing the credential to the PBKDF2 function.

In fact, even nonsense like `--derive=foo` does not produce an error message.

As a consequence, the generated public key differs from the value defined by the specification (which can be obtained with `--derive=NYCSgMaxCfCupvP` in the given example.)

**Comment by glondu** [comment]
Indeed, the hyphens in a secret credential were added for convenience of the human reader, only recently (in version 1.15), but section 4.7 of the specification was not updated (an oversight 😳). They are part of the credential so they should be given when present to the derivation function.

So I see two issues here:

1. Section 4.7 should be updated to cope with the possible presence of hyphens.
1. `belenios-tool credgen --derive=X` should validate its input: it should accept `NYC-SgM-axC-fCu-pvP` (and `NYCSgMaxCfCupvP` for compatibility with previous versions which generated credentials without hyphens), but reject `foo`.

The validation logic specified in section 4.7 is executed only in the web booth at the moment.

**Comment by Vadiml1024** [comment]
Maybe I'm missing something - but generally speaking, wouldn't the fact that secret credential has known character at fixed positions somewhat simplify the work for a potential attacker?

**Comment by glondu** [comment]
I don't think so, what is important is the entropy of the secret credential.
