### ISSUE TITLE
opam init hanging out suddenly

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [glondu/belenios#35]
Hi @glondu ,

* I have past months worked on building Belenios from within a container, and today found out that the automated recipe I had successfully tested does not work anymore. This recipe was using Belenios `1.13`
* I investigated the issue, and tried : 
  * mutliple fixes, 
  * multiple Belenios versions
  * running the recipe on MacOS and inside an Ubuntu in a Circe CI Pipeline
  * and in all cases, I end up falling on the same exact issue : when the recipe tries to run the `opam init`, the process just hangs and stays there without any stdout, and no matter how long I wait, nothing more happens, unless I kill the process

Dismayed by those results, I tried he following , with last commit on master of Belenios (also tried `1.13`), and I end up with the exact same problem : 

```bash
mkdir -p /tmp/belenios-base-env/
git clone https://github.com/glondu/belenios /tmp/belenios-base-env/
cd /tmp/belenios-base-env/
git checkout 1.13
git checkout master
docker build -t beleni8s/base-env -f Dockerfile_base_environment .
```

So there, I think I can say that it is not possible to reproduce Belenios Gitlab CICD Pipeline, which is based on that `Dockerfile_base_environment` :  `Dockerfile_base_environment` fails to build an image for Belenios `1.13` and `master` , for sure.

It really seems like there is an issue with one of the dependencies, and it seems really hard to get any informations from the `opam init` process : Indeed, I am pretty sure I succeded build Belenios `1.13` using my initial original automated recipe

This is very frustrating, since I managed to build a Docker image with one single `belenios-tool` executable file, and I am currently implementing a Belenios REST API , see https://github.com/beleni8s/beleni8s-api/tree/feature/loopback-implttest-1

I am also worried for the stability of the belenios platform : we must be able to "replay" the build of a given Belenios version, and this replay must be stable, especially for a cryptography product. 

I will collaborate gladly to help there

ps: For the record, here is my "hanging" out put : 

```bash
Cloning into 'opam-repository'...
Checking out files: 100% (21207/21207), done.
HEAD is now at a0b420b216 Merge pull request #18747 from fpottier/opam-publish-sek.20201012
[NOTE] Will configure from /home/belenios/.opamrc and then from built-in defaults.
Checking for available remotes: git.
  - you won't be able to use rsync and local repositories unless you install the rsync command on your system.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.


<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[default] Initialised

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-base-compiler.4.11.2] downloaded from https://github.com/ocaml/ocaml/archive/4.11.2.tar.gz

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>

Too long with no output (exceeded 10m0s): context deadline exceeded

```

(below : an execution in an Ubuntu Executor on Circle CI , finishing with a pipeline timeout, which ends up with `Too long with no output (exceeded 10m0s): context deadline exceeded` )

**Comment by glondu** [comment]
I am aware of an issue with installing Belenios build-dependencies (the `opam install` step, which is after `opam init`, and more precisely when installing `menhir`, which changed the URL of its tarballs), which is fixed in the latest `master` and `stable` branches, but might still be present in `1.13` tag.

Your

    docker build -t beleni8s/base-env -f Dockerfile_base_environment .

seems to work for me with latest `master`. I do not expect it to work with `1.13`.

> I am also worried for the stability of the belenios platform : we must be able to "replay" the build of a given Belenios version, and this replay must be stable, especially for a cryptography product.

I agree with this in principle. In the case of Belenios, it should be possible with some efforts but I admit it is not on top of my priority list to keep old versions buildable. 😳

Do you really want to stick to version `1.13`? If so, I would start by removing the `git reset --hard` command from `opam-bootstrap.sh`, then progressively add version constraints to the `opam install` command until it works.

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi @glondu ,

Thank you so very much for such a quick answer, as always.

> I agree with this in principle. In the case of Belenios, it should be possible with some efforts but I admit it is not on top of my priority list to keep old versions buildable.

* I am very happy that this aspect is not on your top priority list : what is, on your priority list surely is something which would take at least two years of full time intensive work, to barely master concepts required to do what is on top of your list
* And I will be honored if any future contribution I deliver on Belenios CICD is accepted by you, which might help for managing Belenios stability. I will contact you when such a first contibution is ready

> 
> I am aware of an issue with installing Belenios build-dependencies (the opam install step, which is after opam init, and more precisely when installing menhir, which changed the URL of its tarballs), which is fixed in the latest master and stable branches, but might still be present in 1.13 tag.
> 

Thank you very much for this valuable info :  This is a path for my investigations which I have not worked on yet, and will, I feed back any further results in this thread.

Regards

**Comment by Jean-Baptiste-Lasselle** [comment]
@glondu More info, Indeed, I found an error about Menhir when it is supposed to be installed by opam : 

```bash
belenios_backend_minimal_build     | [ERROR] The sources of the following couldn't be obtained, aborting:
belenios_backend_minimal_build     |           - menhir.20201122: Bad checksum
belenios_backend_minimal_build     |           - menhirLib.20201122: Bad checksum
belenios_backend_minimal_build     |           - menhirSdk.20201122: Bad checksum
```

I proceed with my investigations, and will update with next informations I consolidate

**Comment by Jean-Baptiste-Lasselle** [comment]
@glondu one question : what is the path of the folder where `opam install` saves the installed ocaml lib/dependencies ?

**Comment by glondu** [comment]
What you say sounds sensible. But I don't know for sure.

**Comment by glondu** [comment]
Does this issue still need to be open? I don't see what is to be done on my side...
