### ISSUE TITLE
"belenios-tool validate" reverses partial decryptions

### ISSUE THREAD

**Issue by hwellmann** [glondu/belenios#38]
According to `belenios-tool validate --help` 

> The result structure contains partial decryptions itself, so partial_decryptions.jsons can be discarded afterwards.

The output `result.json` does contain the partial decryptions, but in reverse order, compared to `partial_decryptions.jsons`.

Is this intentional?

**Comment by glondu** [comment]
Indeed, I confirm the code does what you observe.

Actually, the order of partial decryptions should not matter.
