### ISSUE TITLE
Demo server does not work in git worktrees

### ISSUE THREAD

**Issue by vbgl** [glondu/belenios#39]
The shell scripts in the `demo/` directory to start and stop the server behave differently whether there is a `.git` directory in the current working directory.

I would expect that these scripts behave the same when they are called from the “main working tree” (in which `.git` is a directory) or from a “linked working tree” (in which `.git` is a plain file). However, running `make build-debug-server && ./demo/run-server.sh` works fine from the root of the main worktree but fails within a linked worktree: “BELENIOS_CONFIG must be set!”

**Comment by glondu** [comment]
It should work now.

**Comment by vbgl** [comment]
Thanks. I guess the same patch should be applied to `demo/stop-server.sh`.

**Comment by glondu** [comment]
Right. Done.
