### ISSUE TITLE
limit CAS allowed users to manage elections

### ISSUE THREAD

**Issue by ghouart** [glondu/belenios#47]
It would be useful to be able to limit which users are allowed to manage elections when using CAS authentification for election administrators.
Without it when we configure CAS access in ocsigen.conf any user having a valid account will be able to connect and create elections :-(

**Comment by glondu** [comment]
I've just implemented the following feature: allowed logins can be restricted with an "allowlist" attribute. It should work with any authentication (including CAS). See ocsigenserver.conf.in for an example (with dummy authentication).
