### ISSUE TITLE
access to question<->index mapping on web interface

### ISSUE THREAD

**Issue by danieljeans** [glondu/belenios#54]
I have used belenios for some test votes: it looks a very useful tool, thanks.

I've been using "alternative voting methods" to set up a ranked vote on https://belenios.loria.fr/ in v1.18.
After the vote is counted, participants can see the results in JSON format, in which each (ascii) answer has been assigned to an index [0, 1, ...].
As far as I can tell, there is no way in the web interface to find the mapping between index and the question it corresponds to. 

When I ask for eg the condorcet result it tells me the answer in ascii, but I think the mapping must also be available to both administrator and participants, perhaps best integrated into the JSON data?

**Comment by glondu** [comment]
The indexes are those of the question in the `election.json` file, linked from the election home page, at the bottom. Is more needed?

**Comment by danieljeans** [comment]
thanks, I found it: perfect.
