### ISSUE TITLE
<br> perhaps not working in v1.19

### ISSUE THREAD

**Issue by ghouart** [glondu/belenios#57]
Hi,
It seems that the br with brackets around, added in 1.16 for name, desc ... is not working in v1.19
I used it in 1.17 but now upgrading to 1.19 it is not working 
REM I use a docker file with FROM glondu/beleniosbase:20220223-1

**Comment by pgaudry** [comment]
This was indeed broken.
A fix has been made in the dev version (commits 2ad37c67 and 51378560) and will be available in the next version.

**Comment by glondu** [comment]
Fixed in 1.20.
