### ISSUE TITLE
Is it possible to get a report of all the people who actually voted  in an election?

### ISSUE THREAD

**Issue by DemocraciaPopular** [glondu/belenios#58]
Is it possible to obtain a report of people who actually voted in an election?

It is to give voters an easy way to compare total amount of votes with total amount of voters.

**Comment by glondu** [comment]
Yes.

As as administrator, you can click on the `Voting records` link.

As the credential authority, you can run the following command:

    belenios-tool compute-voters --privcreds /path/to/creds.txt --url https://url/to/election
