### ISSUE TITLE
Dockerized build from source

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [glondu/belenios#7]
Hi, 

I have today tried and build belenios in a docker image build.
My last docker buidl error, obviously is due to the installation process requiring permission to create a namespace. Which is discarded by the Docker build process. Worth mentioning, I also had to force no parallel execution of `make`.

I am curious to ask how can the creation of a linux namespace be required by any software build from source process?

Ma dernière erreur au build `Docker`, est manifestement due au fait que le script de build demande l'autorisation de de créer un namespace, interdit dans un build image conteneur.

Requête surprenante, pour permettre le build d'une application. Puis-je vous demander comment la création d'un namespace peut-être nécesaire à la compilation / packaging / doc. gen. d'un logiciel ?

```bash

=-=-= Generation of env.sh =-=-=


=-=-= Initialization of OPAM root =-=-=

Cloning into 'opam-repository'...
HEAD is now at 0200b39689 Merge pull request #15950 from mseri/release-plplot-5.11.0-1
[WARNING] Running as root is not recommended
[NOTE] Will configure from built-in defaults.
Checking for available remotes: rsync and local, git.
  - you won't be able to use mercurial repositories unless you install the hg command on your system.
  - you won't be able to use darcs repositories unless you install the darcs command on your system.


<><> Fetching repository information ><><><><><><><><><><><><><><><><><><><><><>
[default] Initialised
[WARNING] Running as root is not recommended

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-base-compiler.4.08.1] downloaded from https://github.com/ocaml/ocaml/archive/4.08.1.tar.gz

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
-> installed base-bigarray.base
-> installed base-threads.base
-> installed base-unix.base
[ERROR] The compilation of ocaml-base-compiler failed at "/root/.belenios/opam/opam-init/hooks/sandbox.sh build ./configure --prefix=/root/.belenios/opam/4.08.1 -C".

#=== ERROR while compiling ocaml-base-compiler.4.08.1 =========================#
# context              2.0.5 | linux/x86_64 |  | git+file:///root/.belenios/opam-repository
# path                 ~/.belenios/opam/4.08.1/.opam-switch/build/ocaml-base-compiler.4.08.1
# command              ~/.belenios/opam/opam-init/hooks/sandbox.sh build ./configure --prefix=/root/.belenios/opam/4.08.1 -C
# exit-code            1
# env-file             ~/.belenios/opam/log/ocaml-base-compiler-12049-c743ac.env
# output-file          ~/.belenios/opam/log/ocaml-base-compiler-12049-c743ac.out
### output ###
# Creating new namespace failed: Operation not permitted



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
+- The following actions failed
| - build ocaml-base-compiler 4.08.1
+- 
+- The following changes have been performed (the rest was aborted)
| - install base-bigarray base
| - install base-threads  base
| - install base-unix     base
+- 

<><> ocaml-base-compiler.4.08.1 troubleshooting <><><><><><><><><><><><><><><><>
=> A failure in the middle of the build may be caused by build parallelism
      (enabled by default).
      Please file a bug report at https://github.com/ocaml/ocaml/issues
=> You can try installing again including --jobs=1
      to force a sequential build instead.
# Run eval $(opam env) to update the current shell environment
Switch initialisation failed: clean up? ('n' will leave the switch partially installed) [Y/n] n
The command '/bin/sh -c ./opam-bootstrap.sh' returned a non-zero code: 31
jbl@pegasusio:~/dockerized-belenios$ 
```

### My Dockerfile

```Yaml
FROM debian:9.12-slim


# ARG BELENIOS_SRC_CODE=git@gitlab.com:second-bureau/bellerophon/blockchain-bleue/belenios/belenios.git
ARG BELENIOS_SRC_CODE=https://github.com/glondu/belenios

ARG DEPENDENCIES='git bubblewrap build-essential libgmp-dev libpcre3-dev pkg-config m4 libssl-dev libsqlite3-dev wget ca-certificates zip unzip libncurses-dev uuid-runtime zlib1g-dev libgd-securityimage-perl cracklib-runtime'

RUN apt-get update -y  && apt-get install -y ${DEPENDENCIES}

RUN mkdir -p /belenios/install_home

COPY start.sh /belenios

RUN chmod +x /belenios/*.sh

# RUN git clone $[BELENIOS_SRC_CODE} /belenios/install_home
RUN git clone https://github.com/glondu/belenios /belenios/install_home
WORKDIR /belenios/install_home

RUN chmod +x ./opam-bootstrap.sh
RUN ./opam-bootstrap.sh
RUN make  --jobs=1 all
# RUN BELENIOS_DEBUG=1 make all
# ---
# To make sure the build process completed (almost) without errors
RUN make check
# ---
# 
# To compile the command-line tool, you will need: (installed by 'opam' executable)
RUN opam install atdgen zarith cryptokit uuidm cmdliner
# ---
# Now commpiling belenios command line tool (Belenios CLI)
RUN make  --jobs=1
# ---
# The web server has the following additional dependencies: (installed by 'opam' executable)
RUN opam install calendar eliom csv
# ---
# all the dependencies have been
# installed, the Eliom module can be
# compiled with:
RUN make all

# ---
# Documentation
# -
# To generate HTML files from .md ones, you will need Markdown
ARG DOC_MARKDOWN_DEPENDENCIES='markdown texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra lmodern'
RUN apt-get install -y ${DOC_MARKDOWN_DEPENDENCIES}
# Now generating documentation
RUN make doc




WORKDIR /belenios

CMD [ "/belenios/start.sh" ]

```

* `start.sh` :  

```bash
#!/bin/bash

sleep 100000s
```

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi again @glondu , I have solved my issue : 
* So here you go with the first dockerized version of `belenios`.
* I would like to learn how to use it 
* I know the reference work repo is on INRIA's gitlab
* What would you think of making this project a little more easy to contribute to, on social gits (gtihub/gitlab/Inria's closed to auto registration)
* writing in english for the sake of non-french-speaking readers

**Comment by glondu** [comment]
> I am curious to ask how can the creation of a linux namespace be required by an software build from source process?

Belenios doesn't directly, but opam does use bubblewrap (which does create namespaces) for sandboxing. `opam init` should be called with the `--disable-sandboxing` option to disable sandboxing.

**Comment by Jean-Baptiste-Lasselle** [comment]
> `sandboxing`

thank you very much, indeed what I yesterday did, see https://github.com/pegasus-io/belenios-containers/blob/bffc95e4c2fdef77b87aa2a8b8d1ce417712ad02/opam-bootstrap.sh#L81

So I came to the kindo-fo-a-question : 

* Ok, it is about this package manager `opam`
* Would you smile If I stated "Oh wow this is an ugly package manager, ho does not even know about the contiiner world, that we don't compile anymore using chroot. That containers are containers, and package managers, are package managers (does apt-get launches a chroot to test every installed update of a package ???" 
* _Ocaml, it just makes sense, very much of a language used almost only by academics : no wonder they don't have a better package manager_ : I am wondering if it would take to re-implement you example in another language, just to get an acutal, industry grade package manager. What do you think ?
* Say I learn everything (necessary to prove all) that is inside the `specifications.pdf` , generated with `make doc` : will I be able to prove absolutely every assertions necessary to Zero Knowledge Proof the vote ? 
* Without infos or answer to previous question, I'll assumpe answwer is yes, and I want to thank you for your very quick answer, both here and the detail about the `PGP key`.

Just wanna say too, I have seen journalist stating that a company was using belenios in Nancy, like it was about to  be usable by everyday people : those were jourlnalists, and they were actually being foolish stating that, while actually it was just you, in Nancy, working on it, not any company.
Am I guessing well ? Is there any company that did use your belenios, since 2015?

**Comment by Jean-Baptiste-Lasselle** [comment]
Just a late sry message : I just realized the repo was not public, so I made it public, and https://github.com/pegasus-io/belenios-containers/releases/tag/0.0.1 is available

**Comment by mefyl** [comment]
Some insight and a solution to your problem:

> * Would you smile If I stated "Oh wow this is an ugly package manager, which does not even know about the container world, that we don't compile anymore using chroot. That containers are containers, and package managers, are package managers (does apt-get launches a chroot to test every installed update of a package ???"

I would indeed very much smile : sandboxing offers package reproducibility not only towards the whole system, but between packages themselves and even rules, which is useful even inside containers. People do run builds in containers with capabilities to benefit from those features there.

If you read the manual or the `--help`, you can solve fairly easily : `opam init --disable-sanbox`.

> * _Ocaml, it just makes sense, very much of a language used almost only by academics : no wonder they don't have a better package manager_ : I am wondering if it would not be worth re-implementing your example in another language, just to get an acutal, industry grade package manager. What do you think ?

I think you should educate yourself more on the question instead of frustration ranting. OCaml is an industry grade language with industry grade tooling used by industry leaders (see Tezos, Janestreet amongst many others) and Opam is a better package manager that you have yet understood. Certainly better than apt, which is no achievement at all :)

The one thing I can concede here is that Opam could check for namespacing capabilities write a "if you are an a container, use --disable-sandbox", but that's already going beyond expectations.

**Comment by Jean-Baptiste-Lasselle** [comment]
Hi @mefyl , 

Thank you very much for your answer, which I today read, and followed by a bit of searching,  reading, and thinking. 
* To begin with, I am French, and therefore ranting abitlity is a second nature, if not a requirement. Isn't it bythis provocativeranting,that I today get the opportunity, to learn more? :)
* Now, after reading your message, I went back to the original error I bumped in, in the first place. The `#=== ERROR while compiling ocaml-base-compiler.4.08.1 =========================#` I believe, makes it pretty clear, does it not ? What was going on, while the error occured, is that the `OCaml`  compiler was being built from its source code, am I right ?
* Say I am. So, what is happening is a build from source of a software (which happens to be a compiler), and in that context, `opam`, by default tries and perform that into "an isolated bubble", a namespace. Oh, ok, so OCaml `opam` considers the compilation of a software, should be done in an isolated environment. Well It seems that I do agree with that point of view,since I am myself, building the belenios software into a container, to benefit from that isolation (to be sure of what exactly is around in the system running the compilation task).
* You use the term `package reproducibility` : Well even if you consider that you should always build from source any software that you install  into a system, I would be bold enough to state that compiling your software, is a different task than installing it into the system where you want to use it. I mean, if you use a software,obviously, you will not completely isolate it from the rest of the system, or well why do you need the system at all ? Now there, I am right If I state that what you meant with the `package reproducibility` term, is reproductibility of the build from source process ? 
* Let's go even further now, and assume the answer of my last question is yes : you consider a package manager is something that builds from source softwares. I consider a package manager something that installs a software, into a system (a system = a bunch of softwares that work together). While I use yarn to install npm packages, maven to resolve maven dependencies, go install to install golang dependencies, I have not compiled anything at all. I have just installed a bunch of software (libraries), which will work together as a whole to do something (compile a new software). (and yes, you can install dependencies with maven, with running any maven lifecycle phase).
* And finally, let's go back to my French nature, now : You state that OCaml is an industry grade language, used by industry leaders. Well, to begin with, there are many Industry leaders who use absolutely not industry grade technologies, I believe you, as well, have experienced that. But that's not the French part, here you go with it : 
  * funny that you quote Tezos, JaneStreet amongst many others, 
  * because I have made a bit of research, and I'd say it is kind of likely, that you are interested in your own job, into Blockchains.
  * And that's the funny thing, because I have recently challenged any engineer in this world, to come up with : 
    * a fully automated recipe, able to fully provision, in a private infrastructure, any open source Blockchain 
    * and then show me just one use case of how to use it, to make sure what is provisioned indeed is operational,not just a useless something 
    * I have even dared engineer friends, this very night, to show me such a thing, for Ethereum. I'll pay 3 bottles of Ruinart Champagne if they do, any time. I raise here to 4 bottles. And this is a publicly made commitment, pretty serious, with my full French ID card name.
    * Note, that if you search Github with the "tezos" term, sort by stars number : The first result is the tezos repo itself 15K stars. The next 4/5 repositories are all less than 159 stars, and all of them about Blockchain. Now, I will be ready to discuss calling industry grade any Blockchain related technology, the day I am educated enough to copy paste 1 to a hundred steps from a markdown documentation, get a full Blockchain in a fully private infrastructure, and then perform at least 2/3 standard Blockchain operations, like making a couple of transactions, and verify what to Blockchain claims verifiable. Just like when I verify a GnuPG signature. 
    * Even Giving you A bit of help on the subject : https://github.com/pokusio/le-defi/issues/4 (I admit this is personal work,really not a pleasure to read, still I believe, usable, you have a quorum blockchain ready there, all you have ten to do is to show what to do it, that's another piece of cake)
  * And after that, we can discuss if, in a industry grade technology stack, every software component has to be built from source at installation time. Or what is an isolation state, both isolated enough to guarantee compilation reproductibility, and opened enough for runtime, just for the education.

I think I have a new idea for a blog title : "The ranting French". Sounds great. :)

**Comment by Jean-Baptiste-Lasselle** [comment]
btw @glondu I should have closed the issue long ago, thank you for your help, obviously issue is closed :)

**Comment by Jean-Baptiste-Lasselle** [comment]
Later add on : 
* I have lately designed a new, stable, docker image
* It's main purpose is to make it possible to run belenios without anything but one executable file, nothing related to ocaml env. : will be soon even possible to run it in distroless image
* https://github.com/pegasus-io/belenios-containers/releases/tag/0.0.2 builds belenios 1.13
