### ISSUE TITLE
Verify only new data with belenios-tool

### ISSUE THREAD

**Issue by glondu** [glondu/belenios#71]
`verify` and `verify-diff` perform all possible checks on given election data, which is inefficient when they are repeatedly called in the use case of running an election with just belenios-tool.

See the thread starting at https://sympa.inria.fr/sympa/arc/belenios-discuss/2023-04/msg00001.html

**Comment by mjal** [comment]
Could a `verify-ballot` command that you should run on individual ballot before running `belenios-tool archive add-event` also work ?

**Comment by agoetschm** [comment]
A `verify-ballot` command has been added, as well as a `skip-ballot-check` mode for the `verify` command

- 1e04c09ace4d03809c8817c9c82a6eb2dd20d431
- d37de5d29202fbc2b79da163c72a1a5a60ee3f77

In the case of an election run with belenios-tool, `verify-ballot` can be used on each ballot before casting it. As long as the election is still open, `verify --skip-ballot-check true` will then run its verifications without checking the validity of each ballot, which is where `verify` spends most of its time. The combination of those commands allows to have the same guarantees but it should scale better with the number of voters.

Here is a demo script using those commands: https://gitlab.inria.fr/agoetsch/belenios-cai/-/blob/adfb5e884fd6a36b41481386f3bfa7e92e5c06f5/tests/tool/demo-skip-ballot-check.sh

**Comment by glondu** [comment]
The demo script has also been committed to master: 76d6e14bb35d94cefc5335b05878be24615ee88f
