### ISSUE TITLE
Make texts more consistent

### ISSUE THREAD

**Issue by felagund** [glondu/belenios#75]
Hello, I am now translating a new version into Czech and apparently Weblate has some new tool to spot inconsistencies in translations (different strings having the same translations and vice versa). That also shows inconsistencies in the original. What I found:

1)
https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L2589
"Mail" should be "E-mail
(as on other lines like 870 an d942)

2) (also writing e-mail an email should be unified to either, I suggest e-mail, it uses both all over he place it seems to me)

3) https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L3022
should be "Regenerate and e-mail a password" as on
https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L2966

4) On https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L1766
and https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L752
"Credential" should be "Credentials" - if I am not mistaken, it both pertains to generating credentials for all voters, so plural.

5) https://github.com/glondu/belenios/blob/master/src/web/clients/admin/elections.ml#L1306
and 
https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L2299
should probably be unifie to "and save them in a secure location." - it is used elsewhere more than just plain "securely"

also possible to alter at:
https://github.com/glondu/belenios/blob/master/src/web/common/mails_admin.ml#L241
https://github.com/glondu/belenios/blob/master/src/web/common/mails_admin.ml#L157
https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L2145
https://github.com/glondu/belenios/blob/master/src/web/server/common/site_admin.ml#L804

6)https://github.com/glondu/belenios/blob/master/src/web/clients/admin/admin.ml#L177
and https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L220
should unify, either on (untitled) or (no title)

7) https://github.com/glondu/belenios/blob/master/src/web/clients/admin/trustees.ml#L147
should be "Add a trustee" as in https://github.com/glondu/belenios/blob/master/src/web/clients/admin/trustees.ml#L196

8) https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L2944
and
https://github.com/glondu/belenios/blob/master/src/web/clients/admin/elections.ml#L466
shouldbe unified to "Delete the election"

9) There is a typo here:
https://github.com/glondu/belenios/blob/master/src/web/clients/admin/elections.ml#L1055
(space before colon)
and
https://github.com/glondu/belenios/blob/master/src/web/clients/admin/trustees.ml#L350
(space before question mark)

10) https://github.com/glondu/belenios/blob/master/src/web/clients/admin/account.ml#L79
should be "Log out" like in
https://github.com/glondu/belenios/blob/master/src/web/clients/admin/elections.ml#L1055

11)
https://github.com/glondu/belenios/blob/master/src/web/clients/admin/questions.ml#L436
should be "Condorcet-Schulze method" as in
https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_voter.ml#L1061

12) https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L1891
should be unified with "List of voters:"
https://github.com/glondu/belenios/blob/master/src/web/clients/admin/elections.ml#L817

**Comment by glondu** [comment]
Thank you for your valuable suggestions!

**Comment by felagund** [comment]
@glondu Thank you, weblate complains a lot less now.

There are two things:

1) "Mail" here: https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L1152
shoulbe "E-mail".

2) "List of voters" in these:
https://github.com/glondu/belenios/blob/master/src/web/clients/admin/elections.ml#L817
https://github.com/glondu/belenios/blob/master/src/web/clients/admin/elections.ml#L818
https://github.com/glondu/belenios/blob/master/src/web/server/common/pages_admin.ml#L1816

should be made into "voter list" (it is used more elsewhere).
