### ISSUE TITLE
Election administrator is not available on election home page  

### ISSUE THREAD

**Issue by albanbruder** [glondu/belenios#85]
After upgrading to the latest 2.5 release, I noticed that the poll administrator was not displayed correctly on the election home page. The latest deployment at https://belenios.loria.fr/beta has the same problem. Instead of the configured value, the placeholder N/A is displayed.

Release 2.5:
![image](https://github.com/glondu/belenios/assets/36596731/4d4c9bb3-facd-4f96-b34f-a1f16851837e)

Beta:
![image](https://github.com/glondu/belenios/assets/36596731/443f9f4c-e928-4ea5-88e6-9a5fb239ec19)

**Comment by glondu** [comment]
I can observe the behaviour when using the old admin UI. However, the administrator is displayed correctly when using the new admin UI. Out of curiosity, which version are you upgrading from?

**Comment by albanbruder** [comment]
I have just noticed that the credential authority is affected by the same problem. In the screenshots, this is also shown as N/A.

**Comment by glondu** [comment]
Tentative fix: https://gitlab.inria.fr/belenios/belenios/-/commit/b199bdd06ec1f99b12d1d13ff8387ccd23a41491
